--- 
- hosts: webserver
  become: yes
  tasks:
  
  - name: install apt fail2ban packages
    apt:
      name:
      - fail2ban
      - sendmail
      state: present
      update_cache: yes

  
  - name: override the basic fail2ban configuration with .local file
    copy:
      src: jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
