---
- hosts: 'webserver'
  become: true
  tasks:
#  - name: Install prerequisites
#    apt: >
#      pkg=['perl', 'libnet-ssleay-perl', 'openssl', 'libauthen-pam-perl', 'libpam-runtime', 'libio-pty-perl', 'apt-show-versions', 'python']
  - name: Download deb package Webmin
    get_url: >
      url=https://prdownloads.sourceforge.net/webadmin/webmin_1.941_all.deb
      dest=.
  - name: Install Webmin
    apt: >
      deb=./webmin_1.941_all.deb
  - name: Remove deb package Webmin
    file: >
      path=./webmin_1.941_all.deb
      state=absent
