---
- hosts: webserver
  become: true
  tasks:
  - name: install apache
    apt: name=apache2 state=present update_cache=yes
  - name: Copy ports.conf
    copy: src=../ports.conf dest=/etc/apache2/ports.conf
  - name: Copy default.conf  
    copy: src=../000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf
    notify: restart apache2

  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted